### ISSUE TITLE
Is there any way to disable query log?

### ISSUE THREAD

**Issue by lambdadbmal** [duct-framework/database.sql.hikaricp#11]
Hi,

I want to disable query logs by configuration.
Is there any way to do this or change the log level of query log?

I don't want to enable/disable query log per query like issue #3 .
I Just want to disable all query logs.

Thank you.

**Comment by weavejester** [comment]
Just don't set the `:logger` option. If you don't give it a logger, it doesn't log.

**Comment by lambdadbmal** [comment]
Thank you!
